import {
  analyzeIntent,
  analyzeSniff,
  analyzeVoice,
  detectLang,
  generateBotReply,
  type ChatMessage,
} from "./llm-client.ts"
import {
  buildBridgeTransaction,
  buildComposableBatch,
  buildDepositTransaction,
  buildSwapTransaction,
  buildWithdrawTransaction,
  checkBalance,
  clearCache,
  fetchOptimalVault,
  fetchPortfolio,
  fetchSupportedChains,
  fetchSupportedProtocols,
  fetchTokenPrice,
  fetchVaultComparison,
  fetchVaultDetail,
  getERC20Balance,
  resolveTokenAddress,
  fetchWalletBalances,
  pollBridgeStatus,
} from "./lifi-client.ts"
import {
  generateBridgeReply,
  generateChainsReply,
  generateCompareReply,
  generatePortfolioReply,
  generateProtocolsReply,
  generateTokenPriceReply,
  generateVaultDetailReply,
  generateWithdrawBridgePlan,
  generateWithdrawReply,
} from "./quote-formatter.ts"

export { detectLang, type ChatMessage }

export const CoinBuddyBrain = {
  analyzeVoice,
  analyzeIntent,
  analyzeSniff,
  fetchOptimalVault,
  buildDepositTransaction,
  buildSwapTransaction,
  buildBridgeTransaction,
  buildWithdrawTransaction,
  getERC20Balance,
  generateBotReply,
  generateBridgeReply,
  generateWithdrawReply,
  generateWithdrawBridgePlan,
  fetchVaultComparison,
  fetchVaultDetail,
  fetchPortfolio,
  fetchSupportedChains,
  fetchSupportedProtocols,
  generateCompareReply,
  generateVaultDetailReply,
  generatePortfolioReply,
  generateChainsReply,
  generateProtocolsReply,
  fetchTokenPrice,
  generateTokenPriceReply,
  buildComposableBatch,
  resolveTokenAddress,
  checkBalance,
  clearCache,
  fetchWalletBalances,
  pollBridgeStatus,
}
